id: PEAEA1373
initial_creation_type: input
source_metadata:
  Title: Mahāmāyātantram with Guṇāvatī
  Editor: Rinpoche, Samdong & Vajravallabh Dwivedi
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1992'
  Mahāmāyātantram [guṇavatīṭīkāsahitam]:
    Text Version: Romanized
    Input Personnel: Rashmi Shakya
    Input Date: '2013'
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:57:35.372298'
last_modified_at: '2022-03-08T16:57:35.372307'
